In [4]:
import urllib.request
import pandas as pd

In [5]:
csv_file = pd.read_csv(r"C:\Users\Sebastian Jung\Desktop\Library_Usage.csv")

In [1]:
#print(csv_file)

In [7]:
csv_file.keys()

Index(['Patron Type Code', 'Patron Type Definition', 'Total Checkouts',
       'Total Renewals', 'Age Range', 'Home Library Code',
       'Home Library Definition', 'Circulation Active Month',
       'Circulation Active Year', 'Notice Preference Code',
       'Notice Preference Definition', 'Provided Email Address',
       'Year Patron Registered', 'Outside of County', 'Supervisor District'],
      dtype='object')

In [46]:
#1. Alle Nutzer im Alter zwischen 25 und 34 , die mehr als 10 Medien ausgeliehen haben.
#2. Alle Nutzer die per Post benachrichtigt werden und zur Nutzergruppe Senioren geh√∂ren.

In [8]:
#1. Aufgabe
Nutzergruppe = csv_file[csv_file["Age Range"] == "25 to 34 years"]
Mediennutzung = csv_file[csv_file["Total Checkouts"] >= 10]
Mediennutzung_Nutzergruppe = pd.merge(Nutzergruppe, Mediennutzung)
Mediennutzung_Nutzergruppe.head()

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,0,ADULT,31,22,25 to 34 years,S7,Sunset,April,2016,z,email,True,2010,False,4.0
1,0,ADULT,3002,1689,25 to 34 years,P5,Portola,July,2016,p,phone,True,2004,False,9.0
2,0,ADULT,20,0,25 to 34 years,S7,Sunset,June,2015,z,email,True,2011,False,7.0
3,0,ADULT,102,31,25 to 34 years,M6,Mission,June,2012,z,email,True,2009,False,9.0
4,0,ADULT,45,11,25 to 34 years,P3,Parkside,May,2016,z,email,True,2013,False,4.0

In [52]:
#2. Aufgabe
Postbenachrichtigung = csv_file[csv_file["Notice Preference Definition"] == "print"]
Nutzergruppe_2 = csv_file[csv_file["Patron Type Definition"] == "SENIOR"]
Postbenachrichtigung_Nutzergruppe_2 = pd.merge(Postbenachrichtigung, Nutzergruppe_2)
Postbenachrichtigung_Nutzergruppe_2.head()

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,3,SENIOR,0,0,65 to 74 years,O2,Ocean View,None,None,a,print,False,2015,False,NaN
1,3,SENIOR,259,0,60 to 64 years,X,Main Library,March,2015,a,print,False,2014,False,6.0
2,3,SENIOR,0,0,75 years and over,X,Main Library,None,None,a,print,False,2013,True,NaN
3,3,SENIOR,0,0,75 years and over,X,Main Library,None,None,a,print,False,2013,True,NaN
4,3,SENIOR,0,0,75 years and over,X,Main Library,None,None,a,print,False,2013,True,NaN